import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/_layouts/Header";
import Footer from "@/app/_layouts/Footer";
import { Darker_Grotesque } from "next/font/google";

const darker = Darker_Grotesque({
  subsets: ["latin"],
  weight: ["300","400","500","600","700","800","900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${darker.className}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
